name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push WebAPI Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./gustavoperez.com.br.dotnet8.webapi
        push: true
        tags: guperezdocker/gustavoperez.com.br.dotnet8.webapi:${{ github.sha }}

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./gustavoperez.com.br.angular.ui
        push: true
        tags: guperezdocker/gustavoperez.com.br.angular.ui:${{ github.sha }}

    - name: Set up Kubeconfig
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN }}
    
    - name: Configure Kubeconfig
      run: doctl kubernetes cluster kubeconfig save clu-guperez

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Upgrade WebAPI with Helm
      run: |
        helm upgrade gustavoperez.com.br.dotnet8.webapi ./webapi-helm --set image.tag=${{ github.sha }} --namespace default --install

    - name: Upgrade Frontend with Helm
      run: |
        helm upgrade gustavoperez.com.br.angular.ui ./ui-helm --set image.tag=${{ github.sha }} --namespace default --install
